import 'dart:convert';
import 'dart:io';

void main(List<String> args) async {
  final translationsDir = Directory('assets/translations');
  final outputFile = File('lib/l10n/app_localizations.dart');

  if (!translationsDir.existsSync()) {
    print('Translations directory not found: ${translationsDir.path}');
    exit(1);
  }

  final jsonFiles =
      translationsDir
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.json'))
          .toList();

  if (jsonFiles.isEmpty) {
    print('No JSON files found in translations directory');
    exit(1);
  }

  // Read the first JSON file to get all keys
  final firstFile = jsonFiles.first;
  final content = await firstFile.readAsString();
  final Map<String, dynamic> translations = json.decode(content);

  // Generate the abstract class
  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/generate_localizations.dart');
  buffer.writeln('');
  buffer.writeln('abstract class AppLocalizations {');

  final sortedKeys = translations.keys.toList()..sort();
  for (final key in sortedKeys) {
    final constantName = _toCamelCase(key);
    buffer.writeln('  static const $constantName = \'$key\';');
  }

  buffer.writeln('}');

  // Ensure the output directory exists
  await outputFile.parent.create(recursive: true);

  // Write the generated file
  await outputFile.writeAsString(buffer.toString());

  print('Generated ${outputFile.path} with ${translations.keys.length} keys');
}

String _toCamelCase(String snakeCase) {
  final parts = snakeCase.split('_');
  if (parts.isEmpty) return snakeCase;

  final first = parts.first.toLowerCase();
  final rest = parts
      .skip(1)
      .map(
        (part) =>
            part.isEmpty
                ? ''
                : part[0].toUpperCase() + part.substring(1).toLowerCase(),
      )
      .join('');

  return first + rest;
}
