import 'package:flutter/widgets.dart';
import 'package:vink_sim/l10n/app_localizations.dart';

/// Helper to map dynamic keys to SimLocalizations getters.
/// This is needed because the app uses dynamic keys (strings) for localization,
/// but gen_l10n generates typed getters.
class LocalizationMap {
  static String get(
    BuildContext context,
    String key, {
    List<String>? args,
    Map<String, String>? namedArgs,
  }) {
    final localizations = SimLocalizations.of(context);
    if (localizations == null) {
      return key;
    }

    switch (key) {
      case 'frame_title':
        return localizations.frame_title;
      case 'storage_header_title':
        return localizations.storage_header_title;
      case 'frame_globus_title':
        return localizations.frame_globus_title;
      case 'frame_check_title':
        return localizations.frame_check_title;
      case 'infinity_title':
        return localizations.infinity_title;
      case 'activation_button_title':
        return localizations.activation_button_title;
      case 'what_is_esom':
        return localizations.what_is_esom;
      case 'balance':
        return localizations.balance;
      case 'your_trafic':
        return localizations.your_trafic;
      case 'account_settings':
        return localizations.account_settings;
      case 'purchase_history':
        return localizations.purchase_history;
      case 'traffic_usage':
        return localizations.traffic_usage;
      case 'app_language':
        return localizations.app_language;
      case 'how_to_install_esim':
        return localizations.how_to_install_esim;
      case 'how_to_install_esim2':
        return localizations.how_to_install_esim2;
      case 'support_chat':
        return localizations.support_chat;
      case 'questions_and_answers':
        return localizations.questions_and_answers;
      case 'countries_and_rates':
        return localizations.countries_and_rates;
      case 'top_up_balance':
        return localizations.top_up_balance;
      case 'telegram_support':
        return localizations.telegram_support;
      case 'whatsapp_support':
        return localizations.whatsapp_support;
      case 'email_support':
        return localizations.email_support;
      case 'my_account':
        return localizations.my_account;
      case 'app_language_title':
        return localizations.app_language_title;
      case 'app_language_ru':
        return localizations.app_language_ru;
      case 'app_language_en':
        return localizations.app_language_en;
      case 'start_registration':
        return localizations.start_registration;
      case 'download':
        return localizations.download;
      case 'close':
        return localizations.close;
      case 'install_esim':
        return localizations.install_esim;
      case 'connection_wait_message':
        return localizations.connection_wait_message;
      case 'connection_retry_instruction':
        return localizations.connection_retry_instruction;
      case 'support_chat2':
        return localizations.support_chat2;
      case 'success_message':
        return localizations.success_message;
      case 'fast_description_step1':
        return localizations.fast_description_step1;
      case 'fast_description_step2':
        return localizations.fast_description_step2;
      case 'fast_description_step3':
        return localizations.fast_description_step3;
      case 'fast_description_step4':
        return localizations.fast_description_step4;
      case 'fast_selected_row':
        return localizations.fast_selected_row;
      case 'manual_selected_row':
        return localizations.manual_selected_row;
      case 'qr_code_selected_row':
        return localizations.qr_code_selected_row;
      case 'to_another_device_selected_row':
        return localizations.to_another_device_selected_row;
      case 'coming_soon':
        return localizations.coming_soon;
      case 'how_does_it_work':
        return localizations.how_does_it_work;
      case 'esim_description1':
        return localizations.esim_description1;
      case 'esim_description2':
        return localizations.esim_description2;
      case 'qr_code_description':
        return localizations.qr_code_description;
      case 'send_qr':
        return localizations.send_qr;
      case 'another_device_description_warning':
        return localizations.another_device_description_warning;
      case 'another_device_description1':
        return localizations.another_device_description1;
      case 'another_device_description2':
        return localizations.another_device_description2;
      case 'another_device_description3':
        return localizations.another_device_description3;
      case 'another_device_description5':
        return localizations.another_device_description5;
      case 'another_device_description_important':
        return localizations.another_device_description_important;
      case 'manual_description1':
        return localizations.manual_description1;
      case 'adress_sm_dp':
        return localizations.adress_sm_dp;
      case 'activation_code':
        return localizations.activation_code;
      case 'tariffs_by_countries':
        return localizations.tariffs_by_countries;
      case 'guide_for_esim_settings':
        return localizations.guide_for_esim_settings;
      case 'smth_more':
        return localizations.smth_more;
      case 'tariffs_and_countries':
        return localizations.tariffs_and_countries;
      case 'balance_and_esim_activation':
        return localizations.balance_and_esim_activation;
      case 'profile_setup_guide':
        return localizations.profile_setup_guide;
      case 'ready_to_travel_message':
        return localizations.ready_to_travel_message;
      case 'high_speed_low_cost':
        return localizations.high_speed_low_cost;
      case 'countries_in_one_esim':
        return localizations.countries_in_one_esim;
      case 'activate_esim':
        return localizations.activate_esim;
      case 'auth_with_the_help_of':
        return localizations.auth_with_the_help_of;
      case 'whats_app':
        return localizations.whats_app;
      case 'email':
        return localizations.email;
      case 'mobile_num_whats_app_description':
        return localizations.mobile_num_whats_app_description;
      case 'email_description':
        return localizations.email_description;
      case 'auth_and_registration':
        return localizations.auth_and_registration;
      case 'continue_with_apple':
        return localizations.continue_with_apple;
      case 'continue_with_google':
        return localizations.continue_with_google;
      case 'continue_with_email':
        return localizations.continue_with_email;
      case 'esim_is_activated':
        return localizations.esim_is_activated;
      case 'important':
        return localizations.important;
      case 'attention':
        return localizations.attention;
      case 'now_you_need_to_install_esim':
        return localizations.now_you_need_to_install_esim;
      case 'you_can_activate_esim_only_once':
        return localizations.you_can_activate_esim_only_once;
      case 'show_qr':
        return localizations.show_qr;
      case 'select_country':
        return localizations.select_country;
      case 'search_countries':
        return localizations.search_countries;
      case 'add_esim':
        return localizations.add_esim;
      case 'manage_more_esims':
        return localizations.manage_more_esims;
      case 'to_add':
        return localizations.to_add;
      case 'top_up':
        return localizations.top_up;
      case 'select_level':
        return localizations.select_level;
      case 'low_level':
        return localizations.low_level;
      case 'medium_level':
        return localizations.medium_level;
      case 'high_level':
        return localizations.high_level;
      case 'enter_amount_description':
        return localizations.enter_amount_description;
      case 'balance_15_description':
        return localizations.balance_15_description(
          namedArgs?['amount'] ?? args?.first ?? '',
        );
      case 'all_countries_and_tariffs':
        return localizations.all_countries_and_tariffs;
      case 'choose_payment_method':
        return localizations.choose_payment_method;
      case 'auto_top_up':
        return localizations.auto_top_up;
      case 'auto_top_up_description':
        return localizations.auto_top_up_description;
      case 'enter_code':
        return localizations.enter_code;
      case 'code_sent_message':
        return localizations.code_sent_message;
      case 'enter_code_below':
        return localizations.enter_code_below;
      case 'login_another_way':
        return localizations.login_another_way;
      case 'resend_code':
        return localizations.resend_code;
      case 'resend_code_timer':
        return localizations.resend_code_timer(
          namedArgs?['seconds'] ?? args?.first ?? '',
        );
      case 'step_number':
        return localizations.step_number(
          namedArgs?['step'] ?? args?.first ?? '',
        );
      case 'code_sent_to_number':
        return localizations.code_sent_to_number;
      case 'checking':
        return localizations.checking;
      case 'confirm_code':
        return localizations.confirm_code;
      case 'login_different_way':
        return localizations.login_different_way;
      case 'resend_code_after_seconds':
        return localizations.resend_code_after_seconds(
          namedArgs?['seconds'] ?? args?.first ?? '',
        );
      case 'account_top_up':
        return localizations.account_top_up;
      case 'packages_from_1_dollar':
        return localizations.packages_from_1_dollar;
      case 'start':
        return localizations.start;
      case 'dollars_on_account':
        return localizations.dollars_on_account(
          namedArgs?['amount'] ?? args?.first ?? '',
        );
      case 'language':
        return localizations.language;
      case 'russian':
        return localizations.russian;
      case 'chinese':
        return localizations.chinese;
      case 'enter_amount_top_up_description':
        return localizations.enter_amount_top_up_description;
      case 'flex_travel_esim_works_worldwide':
        return localizations.flex_travel_esim_works_worldwide;
      case 'loading':
        return localizations.loading;
      case 'pay_money':
        return localizations.pay_money(
          namedArgs?['amount'] ?? args?.first ?? '',
        );
      case 'in_europe':
        return localizations.in_europe;
      case 'in_dubai':
        return localizations.in_dubai;
      case 'in_asia':
        return localizations.in_asia;
      case 'monaco':
        return localizations.monaco;
      case 'enter_verification_code':
        return localizations.enter_verification_code;
      case 'login_using_another_method':
        return localizations.login_using_another_method;
      case 'send_again':
        return localizations.send_again;
      case 'did_not_receive_the_code':
        return localizations.did_not_receive_the_code;
      case 'sended_six_digit_code':
        return localizations.sended_six_digit_code(
          namedArgs?['phone'] ?? args?.first ?? '',
        );
      case 'april_2023':
        return localizations.april_2023;
      case 'balance_refill':
        return localizations.balance_refill;
      case 'my_esims':
        return localizations.my_esims;
      case 'send_error':
        return localizations.send_error;
      case 'otp_resent':
        return localizations.otp_resent;
      case 'otp_fail':
        return localizations.otp_fail;
      case 'otp_success':
        return localizations.otp_success;
      case 'payment_fail':
        return localizations.payment_fail;
      case 'enter_top_up_amount':
        return localizations.enter_top_up_amount;
      case 'select_level_title':
        return localizations.select_level_title;
      case 'low_level_balance':
        return localizations.low_level_balance;
      case 'medium_level_balance':
        return localizations.medium_level_balance;
      case 'high_level_balance':
        return localizations.high_level_balance;
      case 'error':
        return localizations.error;
      case 'not_available':
        return localizations.not_available;
      case 'gigabytes':
        return localizations.gigabytes;
      case 'balance_prefix':
        return localizations.balance_prefix;
      case 'step':
        return localizations.step;
      case 'logout':
        return localizations.logout;
      case 'logout_confirmation_title':
        return localizations.logout_confirmation_title;
      case 'logout_confirmation_message':
        return localizations.logout_confirmation_message;
      case 'cancel':
        return localizations.cancel;
      case 'in_country':
        return localizations.in_country;
      case 'select_sim_card':
        return localizations.select_sim_card;
      case 'sim_card_fallback':
        return localizations.sim_card_fallback;
      case 'on_balance':
        return localizations.on_balance;
      case 'select_for_top_up':
        return localizations.select_for_top_up;
      case 'sim_card_default':
        return localizations.sim_card_default;
      case 'esim_is_activating':
        return localizations.esim_is_activating;
      default:
        return key;
    }
  }
}
